apiVersion: v1
kind: Service
metadata:
  name: prism-auth
  namespace: prism
spec:
  selector:
    app: auth-service
  ports:
    - port: 8082
      targetPort: 8082
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: prism-inventory
  namespace: prism
spec:
  selector:
    app: inventory-service
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: prism-pos
  namespace: prism
spec:
  selector:
    app: pos-service
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
